version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Vilnius
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci

  - package-ecosystem: pip
    directory: /requirements
    schedule:
      interval: weekly
      day: monday
      time: "06:15"
      timezone: Europe/Vilnius
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
