"""Provider-neutral Integrations Module public surface."""

from ctower_kernel.integrations.interface import (
    AmbiguousWrite,
    CloseExternalIssue,
    CloseExternalIssueResult,
    CloseFailure,
    ConnectorAttempt,
    ConnectorClaim,
    ConnectorCursorToken,
    ConnectorLabelMapping,
    ConnectorLink,
    ConnectorReceipt,
    ConnectorRegistration,
    ConnectorStore,
    ConnectorSyncBatch,
    ConnectorSyncError,
    ExternalIssue,
    ExternalIssuePage,
    FailureReason,
    FetchFailure,
    FetchIssuePage,
    FetchIssuePageResult,
    IssueConnector,
    RetryClass,
    WriteDisposition,
)
from ctower_kernel.integrations.service import ConnectorRetryExecutor, IssueConnectorService

__all__ = [
    "AmbiguousWrite",
    "CloseExternalIssue",
    "CloseExternalIssueResult",
    "CloseFailure",
    "ConnectorAttempt",
    "ConnectorClaim",
    "ConnectorCursorToken",
    "ConnectorLabelMapping",
    "ConnectorLink",
    "ConnectorReceipt",
    "ConnectorRegistration",
    "ConnectorRetryExecutor",
    "ConnectorStore",
    "ConnectorSyncBatch",
    "ConnectorSyncError",
    "ExternalIssue",
    "ExternalIssuePage",
    "FailureReason",
    "FetchFailure",
    "FetchIssuePage",
    "FetchIssuePageResult",
    "IssueConnector",
    "IssueConnectorService",
    "RetryClass",
    "WriteDisposition",
]
