"""Authored OpenAPI operation metadata inventory used by contract tests."""

from __future__ import annotations

from ._request_proposal_inventory import REQUEST_PROPOSAL_OPERATION_METADATA
from ._ruling_inventory import RULING_OPERATION_METADATA

_EXPECTED_OPERATION_METADATA: dict[str, tuple[object, bool, str, object, bool]] = {
    "addKnowledgeDocument": ("knowledge add", True, "allowed", None, False),
    "addTicketComment": ("ticket comment add", True, "allowed", None, False),
    "addTicketRelation": ("ticket relation add", True, "allowed", None, False),
    "allowConsoleSession": (None, True, "forbidden", None, False),
    "appendAttentionFinding": ("attention finding append", True, "allowed", None, False),
    "appendSpawnTransition": ("spawn transition", True, "allowed", None, False),
    **REQUEST_PROPOSAL_OPERATION_METADATA,
    "appendCtowerProjectImportCorrection": (
        "migration ctower-project correction append",
        True,
        "forbidden",
        "operator",
        False,
    ),
    **RULING_OPERATION_METADATA,
    "applyCompanyBundle": ("company bundle apply", True, "allowed", None, False),
    "applyCtowerProjectImportBatch": (
        "migration ctower-project import",
        True,
        "forbidden",
        "migration_importer",
        False,
    ),
    "applyTicketIntent": (
        ["ticket admit", "ticket defer", "ticket block", "ticket unblock", "ticket reopen"],
        True,
        "allowed",
        None,
        False,
    ),
    "applyTicketLabel": ("ticket label apply", True, "allowed", None, False),
    "bindCtowerProjectAliasPlan": (
        "migration ctower-project plan",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "bindCtowerProjectExportEquality": (
        "migration ctower-project export",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "bindDreamLane": ("dream-lane bind", True, "forbidden", None, False),
    "bootstrapFirstTenant": ("bootstrap first-tenant", True, "forbidden", None, False),
    "captureRequest": ("request capture", True, "allowed", None, False),
    "assignRequestOwner": ("request owner assign", True, "allowed", None, False),
    "changeTicketAssignment": ("ticket assign", True, "allowed", None, False),
    "changeTicketPriority": ("ticket prioritize", True, "allowed", None, False),
    "consumeReviewDispatchEffect": (
        "ticket review-dispatch consume",
        True,
        "allowed",
        None,
        False,
    ),
    "consumeDreamDispatchEffect": ("dream-dispatch consume", True, "allowed", None, False),
    "commitCtowerProjectDevelopmentEpoch": (
        "migration ctower-project commit-development-epoch",
        False,
        "forbidden",
        "operator",
        True,
    ),
    "createCtowerProjectImportRun": (
        "migration ctower-project inventory",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "createSpawnRecord": ("spawn record", True, "allowed", None, False),
    "createTicket": (["ticket capture", "ticket create"], True, "allowed", None, False),
    "exportCompanyBundle": ("company bundle export", False, "forbidden", None, False),
    "importEstateCompanyRecords": (
        "migration ctower-company-record import",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "importEstateInbox": ("migration ctower-inbox import", True, "forbidden", "operator", False),
    "importEstateKnowledge": (
        "migration ctower-knowledge import",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "importEstateRulings": (
        "migration ctower-ruling import",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "evaluateRequestClosure": ("request closure evaluate", True, "allowed", None, False),
    "finalizeCtowerProjectImportRun": (
        "migration ctower-project reconcile",
        True,
        "forbidden",
        "operator",
        False,
    ),
    "freezeProofCriteria": ("ticket criteria freeze", True, "allowed", None, False),
    "getBoard": ("board query", False, "forbidden", None, False),
    "getControlHealth": ("control health", False, "forbidden", None, False),
    "getKnowledgeDocument": ("knowledge get", False, "forbidden", None, False),
    "getMorningDigest": ("digest morning", False, "forbidden", None, False),
    "getMovementAtom": (None, False, "forbidden", "authenticated", False),
    "getCtowerProjectCutoverHealth": (
        "migration ctower-project verify",
        False,
        "forbidden",
        "authenticated",
        False,
    ),
    "getCtowerProjectImportRun": (
        "migration ctower-project run get",
        False,
        "forbidden",
        "operator",
        False,
    ),
    "getProjectDelivery": (
        "project delivery query",
        False,
        "forbidden",
        "authenticated",
        False,
    ),
    "getSpawnRecord": ("spawn show", False, "forbidden", "authenticated", False),
    "getSyntheticWorkflowRun": ("synthetic query", False, "forbidden", None, False),
    "getTicket": (["ticket query", "ticket show"], False, "forbidden", None, False),
    "getTicketTimeline": ("ticket timeline", False, "forbidden", None, False),
    "issueSeatCredential": ("credential seat issue", True, "forbidden", None, False),
    "acknowledgeInboxMessage": ("inbox ack", True, "allowed", None, False),
    "listInboxCorrespondents": ("inbox correspondents", False, "forbidden", None, False),
    "listInboxThreads": ("inbox list", False, "forbidden", None, False),
    "listDreamDispatchEffects": (
        "dream-dispatch list",
        False,
        "forbidden",
        None,
        False,
    ),
    "listKnowledgeDocuments": ("knowledge list", False, "forbidden", None, False),
    "listVisibleConsoleSessions": (None, False, "forbidden", None, False),
    "listTicketAssignments": ("ticket assignments", False, "forbidden", None, False),
    "listTicketAuditEvents": ("ticket audit", False, "forbidden", None, False),
    "listProjectEvents": (
        "project events",
        False,
        "forbidden",
        "authenticated",
        False,
    ),
    "listTicketMovement": (
        "project movement",
        False,
        "forbidden",
        "authenticated",
        False,
    ),
    "listProjectSessions": (
        "session project",
        False,
        "forbidden",
        "authenticated",
        False,
    ),
    "listRequests": ("request list", False, "forbidden", None, False),
    "listReviewDispatchEffects": (
        "ticket review-dispatch list",
        False,
        "forbidden",
        None,
        False,
    ),
    "listSpawnRecords": ("spawn list", False, "forbidden", "authenticated", False),
    "listTicketSessions": ("session ticket", False, "forbidden", None, False),
    "planCompanyBundle": ("company bundle plan", False, "forbidden", None, False),
    "mintConsoleViewGrant": (None, True, "forbidden", None, False),
    "prepareCtowerProjectCutover": (
        "migration ctower-project prepare",
        False,
        "forbidden",
        "operator",
        True,
    ),
    "prioritizeRequest": ("request prioritize", True, "allowed", None, False),
    "promoteIntakeEvent": ("intake promote", True, "allowed", None, False),
    "promoteInboxThread": ("inbox promote", True, "allowed", None, False),
    "readInboxThread": ("inbox read", False, "forbidden", None, False),
    "readInboxMessageState": ("inbox read-state", False, "forbidden", None, False),
    "readPoolLimits": ("pools show", False, "forbidden", "authenticated", False),
    "recordPoolObservation": ("pools observe", True, "allowed", None, False),
    "recordAttentionFindingDisposition": (
        "attention finding disposition",
        True,
        "allowed",
        None,
        False,
    ),
    "recordOutboxPoisonDisposition": (
        "ops outbox poison dispose",
        True,
        "allowed",
        None,
        False,
    ),
    "recordTicketChangeReference": (
        "ticket change-reference add",
        True,
        "allowed",
        None,
        False,
    ),
    "recordProofEvidence": ("ticket evidence add", True, "allowed", None, False),
    "recordTicketSessionFact": (
        ["session transition", "session close"],
        True,
        "allowed",
        None,
        False,
    ),
    "recordProofVerdict": ("ticket gate verdict", True, "allowed", None, False),
    "renewConsoleViewGrant": (None, True, "forbidden", None, False),
    "relateRequestTicket": ("request ticket relate", True, "allowed", None, False),
    "reportCtowerProjectFenceObservation": (
        "migration ctower-project fence observe",
        True,
        "forbidden",
        "fence_observer",
        False,
    ),
    "resolveCloseWorkflow": ("ticket resolve", True, "allowed", None, False),
    "revokeSeatCredential": ("credential seat revoke", True, "forbidden", None, False),
    "revokeConsoleSession": (None, True, "forbidden", None, False),
    "runSyntheticWorkflow": ("synthetic run", True, "allowed", None, False),
    "ingestInboxNotification": ("inbox notify", True, "allowed", None, False),
    "sendInboxMessage": ("inbox send", True, "allowed", None, False),
    "setRequestBlocker": ("request blocker set", True, "allowed", None, False),
    "setConsoleKillSwitch": (None, True, "forbidden", None, False),
    "startTicketSession": ("session start", True, "allowed", None, False),
    "startTicketWorkflow": ("ticket workflow start", True, "allowed", None, False),
    "streamConsoleEvents": (None, True, "forbidden", None, False),
    "submitIntake": ("intake submit", True, "allowed", None, False),
    "transferTicketCustody": ("ticket custody transfer", True, "allowed", None, False),
    "transitionWorkflow": ("ticket transition", True, "allowed", None, False),
    "triageRequest": ("request triage", True, "allowed", None, False),
    "validateCompanyBundle": ("company bundle validate", False, "forbidden", None, False),
}
